apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: iot-system
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: redis
          image: redis:7
          command: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: iot-system
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
